"""Narrow hierarchical CAE lifecycle facade."""
from __future__ import annotations
from .state_repository import StateKey as StateKey
from .data_adapter import _as_population as _as_population
from .data_adapter import _x_matrix as _x_matrix
from .data_adapter import _load_training_data as _load_training_data
from .data_adapter import training_data_from_session as training_data_from_session
from .data_adapter import _unique_training_data as _unique_training_data
from .data_adapter import _costs_from_samples as _costs_from_samples
from .data_adapter import _build_current_schema as _build_current_schema
from .state_repository import _training_success_metadata as _training_success_metadata
from .state_repository import _component_payload as _component_payload
from .state_repository import strategy_signature_for_workspace as strategy_signature_for_workspace
from .state_repository import workspace_state_key as workspace_state_key
from .state_repository import _select_device as _select_device
from .state_repository import train as train
from .state_repository import train_with_config as train_with_config
from .state_repository import _is_usable_state as _is_usable_state
from .state_repository import has_trained_state as has_trained_state
from .state_repository import latest_state_generation as latest_state_generation
from .state_repository import reset_workspace_state as reset_workspace_state
from .state_repository import _state_for_config as _state_for_config
from .state_repository import _recover_latest_state as _recover_latest_state
from .state_repository import _recover_state_from_checkpoint as _recover_state_from_checkpoint
from .state_repository import _require_state as _require_state
from .projection import _predict_members as _predict_members
from .projection import predict_raw_data as predict_raw_data
from .projection import predict_population as predict_population
from .projection import predict_applicability as predict_applicability
from .projection import predict_field_at_coordinates as predict_field_at_coordinates
