from __future__ import annotations

import json
import math
import os
from pathlib import Path
import subprocess
import sys
from types import SimpleNamespace

import numpy as np
import yadof

from yadof.config import load_config
from yadof.evaluate_manager import evaluate_population, prepare_job, run_smoke_test
from yadof.evaluate_manager.types import JobResult
from yadof.recorded_data import list_records
from yadof.workspace_init import init_workspace


def _workspace(tmp_path: Path, name: str) -> Path:
    root = tmp_path / name
    init_workspace(root)
    (root / "config.py").write_text(
        'EVALUATION_MODE = "distributed"\n'
        'HTCONDOR_REQUEST_MEMORY = "10MB"\n'
        'HTCONDOR_REQUEST_DISK = "100KB"\n'
        "HTCONDOR_REQUEST_CPUS = 3\n"
        "HTCONDOR_POLL_SEC = 0.1\n",
        encoding="utf-8",
    )
    return root


def _completed_result(job) -> JobResult:
    raw_dir = job.directory / "rawData"
    raw_dir.mkdir(exist_ok=True)
    raw_path = raw_dir / "response.npz"
    np.savez(
        raw_path,
        values=np.asarray(0.25, dtype=float),
        metadata=json.dumps(
            {"schema_version": 1, "shape": [], "rawdata_name": "response"}
        ),
    )
    return JobResult(
        job_name=job.name,
        job_dir=job.directory,
        status="done",
        unnormalized_variables=job.unnormalized_variables,
        raw_data_paths=(raw_path,),
        metadata={
            "job_name": job.name,
            "status": "done",
            "engine": "htcondor",
            "generation_index": job.generation_index,
            "run_id": job.run_id,
        },
    )


def test_packaged_submit_file_uses_worker_bootstrap_and_unlimited_smoke(
    tmp_path,
):
    from yadof.evaluate_manager.condor_runner import write_condor_submit_file

    workspace = _workspace(tmp_path, "submit")
    config = load_config(workspace)
    job = prepare_job(
        workspace,
        (0.5,),
        config=config,
        mode="distributed",
        timeout_sec=None,
        generation_index=None,
    )

    submit_path = write_condor_submit_file(
        workspace, job, config=config
    )
    text = submit_path.read_text(encoding="utf-8")

    assert "Auto-generated by yadof.evaluate_manager" in text
    assert "executable = workflow.py" in text
    assert "allowed_execute_duration" not in text
    assert "request_cpus = 3" in text
    assert "request_memory = 10MB" in text
    assert "request_disk = 100KB" in text
    transfer = next(
        line for line in text.splitlines() if line.startswith("transfer_input_files")
    )
    assert "sitecustomize.py" in transfer
    assert "worker_misc.py" in transfer
    assert "yadof_worker_config.json" in transfer
    worker_config = json.loads(
        (job.directory / "yadof_worker_config.json").read_text(encoding="utf-8")
    )
    assert worker_config["effective_config"]["EVALUATION_MODE"]["value"] == "distributed"
    assert "HTCONDOR_REQUEST_MEMORY" in worker_config["effective_config"]


def test_distributed_population_and_smoke_keep_shape_and_callback(
    tmp_path, monkeypatch
):
    from yadof.evaluate_manager import condor_runner

    workspace = _workspace(tmp_path, "dispatch")
    callbacks: list[str] = []

    def fake_run(workspace_arg, jobs, **kwargs):
        assert workspace_arg.root == workspace.resolve()
        assert kwargs["timeout_sec"] is not None
        kwargs["after_jobs_submitted"]()
        return tuple(_completed_result(job) for job in jobs)

    monkeypatch.setattr(condor_runner, "run_condor_jobs", fake_run)
    costs = evaluate_population(
        workspace,
        ((0.25,), (0.75,)),
        mode="distributed",
        after_jobs_submitted=lambda: callbacks.append("submitted"),
    )
    assert costs == ((0.25,), (0.25,))
    assert callbacks == ["submitted"]
    assert len(list_records(workspace)) == 2

    def fake_smoke(workspace_arg, jobs, **kwargs):
        assert kwargs["timeout_sec"] is None
        assert len(jobs) == 1
        return (_completed_result(jobs[0]),)

    monkeypatch.setattr(condor_runner, "run_condor_jobs", fake_smoke)
    assert run_smoke_test(workspace, mode="distributed") == ((0.25,),)


def test_distributed_submit_failure_is_per_individual_and_diagnosable(
    tmp_path, monkeypatch
):
    from yadof.evaluate_manager import condor_runner

    workspace = _workspace(tmp_path, "failure")

    def missing_condor(*_args, **_kwargs):
        raise OSError("condor_submit is unavailable")

    monkeypatch.setattr(condor_runner.subprocess, "run", missing_condor)
    costs = evaluate_population(
        workspace, ((0.25,), (0.75,)), mode="distributed", timeout_sec=0.1
    )
    assert all(math.isinf(row[0]) for row in costs)
    records = list_records(workspace)
    assert len(records) == 2
    assert all(row["status"] == "error" for row in records)
    assert all(
        row["job_metadata"]["failure_stage"] == "submit" for row in records
    )


def test_resource_calibration_reads_only_the_selected_workspace(
    tmp_path, monkeypatch
):
    from yadof.evaluate_manager import resource_requests

    workspace_a = _workspace(tmp_path, "calibration_a")
    workspace_b = _workspace(tmp_path, "calibration_b")
    config_a = load_config(workspace_a)
    config_b = load_config(workspace_b)
    job_a = SimpleNamespace(generation_index=0, run_id="run-a")
    job_b = SimpleNamespace(generation_index=0, run_id="run-b")
    records_by_root = {
        workspace_a.resolve(): (
            {
                "status": "completed",
                "generation_index": None,
                "job_metadata": {
                    "engine": "htcondor",
                    "condor_memory_usage_mib": 512,
                    "condor_disk_usage_kib": 2048,
                },
            },
        ),
        workspace_b.resolve(): (),
    }

    monkeypatch.setattr(
        resource_requests.recorded_data_api,
        "list_records",
        lambda workspace: records_by_root[Path(workspace.root).resolve()],
    )
    request_a = resource_requests.request_for_job(
        workspace_a, job_a, config=config_a
    )
    request_b = resource_requests.request_for_job(
        workspace_b, job_b, config=config_b
    )
    assert request_a.source == "smoke_calibration"
    assert request_a.memory_mib == 1024
    assert request_b.source == "configured_default"
    assert request_b.memory_mib == 10


def _run_worker_bootstrap(job_dir: Path) -> subprocess.CompletedProcess[str]:
    environment = os.environ.copy()
    package_parent = Path(yadof.__file__).resolve().parent.parent
    environment["PYTHONPATH"] = os.pathsep.join((str(job_dir), str(package_parent)))
    return subprocess.run(
        [sys.executable, "-c", "pass"],
        cwd=job_dir,
        env=environment,
        capture_output=True,
        text=True,
        timeout=20,
        check=False,
    )


def test_worker_bootstrap_reports_version_mismatch(tmp_path):
    workspace = _workspace(tmp_path, "version_mismatch")
    job = prepare_job(
        workspace,
        (0.5,),
        mode="distributed",
        timeout_sec=None,
    )
    config_path = job.directory / "yadof_worker_config.json"
    config = json.loads(config_path.read_text(encoding="utf-8"))
    config["yadof_version"] = "999.0.0"
    config_path.write_text(json.dumps(config), encoding="utf-8")

    result = _run_worker_bootstrap(job.directory)

    assert result.returncode == 86
    metadata = json.loads(
        (job.directory / "individual_metadata.json").read_text(encoding="utf-8")
    )
    assert metadata["failure_stage"] == "worker_bootstrap"
    assert metadata["expected_yadof_version"] == "999.0.0"
    assert metadata["actual_yadof_version"]


def test_worker_bootstrap_reports_missing_package(tmp_path):
    workspace = _workspace(tmp_path, "missing_package")
    job = prepare_job(
        workspace,
        (0.5,),
        mode="distributed",
        timeout_sec=None,
    )
    (job.directory / "yadof.py").write_text(
        "raise ImportError('synthetic missing worker package')\n",
        encoding="utf-8",
    )

    result = _run_worker_bootstrap(job.directory)

    assert result.returncode == 86
    metadata = json.loads(
        (job.directory / "individual_metadata.json").read_text(encoding="utf-8")
    )
    assert metadata["failure_stage"] == "worker_bootstrap"
    assert metadata["actual_yadof_version"] == ""
    assert "not importable" in metadata["error_message"]


def test_time_limit_calibration_is_workspace_local(tmp_path, monkeypatch):
    from yadof.evaluate_manager import time_limits
    from yadof.evaluate_manager.types import JobSpec

    workspace_a = _workspace(tmp_path, "time_a")
    workspace_b = _workspace(tmp_path, "time_b")
    config_a = load_config(workspace_a)
    config_b = load_config(workspace_b)
    job = JobSpec(
        name="generation-zero",
        directory=workspace_a / "jobs/generation-zero",
        unnormalized_variables=(0.5,),
        generation_index=0,
        run_id="run-a",
    )
    records = {
        workspace_a.resolve(): (
            {
                "status": "completed",
                "generation_index": None,
                "recorded_at": "2026-07-18T10:00:00+00:00",
                "job_metadata": {
                    "engine": "htcondor",
                    "condor_remote_wall_clock_sec": 12.0,
                    "condor_cumulative_suspension_sec": 2.0,
                },
            },
        ),
        workspace_b.resolve(): (),
    }
    monkeypatch.setattr(
        time_limits.recorded_data_api,
        "list_records",
        lambda selected: records[Path(selected.root).resolve()],
    )

    limit_a = time_limits.time_limit_for_job(workspace_a, job, config=config_a)
    limit_b = time_limits.time_limit_for_job(workspace_b, job, config=config_b)

    assert limit_a.source == "smoke_calibration"
    assert limit_a.seconds == 20
    assert limit_b.source == "configured_fallback"
