from __future__ import annotations

import json
import math
from pathlib import Path
import subprocess
import sys
from types import SimpleNamespace
import zipfile

import numpy as np

from yadof.config import load_config
from yadof.evaluate_manager import evaluate_population, prepare_job, run_smoke_test
from yadof.evaluate_manager.types import JobResult
from yadof.recorded_data import list_records
from yadof.workspace.init import init_workspace


def _workspace(tmp_path: Path, name: str) -> Path:
    root = tmp_path / name
    init_workspace(root)
    (root / "config.py").write_text(
        'EVALUATION_MODE = "distributed"\n'
        'HTCONDOR_REQUEST_MEMORY = "10MB"\n'
        'HTCONDOR_REQUEST_DISK = "100KB"\n'
        "HTCONDOR_REQUEST_CPUS = 3\n"
        "HTCONDOR_POLL_SEC = 0.1\n",
        encoding="utf-8",
    )
    return root


def _completed_result(job) -> JobResult:
    raw_dir = job.directory / "rawData"
    raw_dir.mkdir(exist_ok=True)
    raw_path = raw_dir / "response.npz"
    np.savez(
        raw_path,
        values=np.asarray(0.25, dtype=float),
        metadata=json.dumps(
            {"schema_version": 1, "shape": [], "rawdata_name": "response"}
        ),
    )
    return JobResult(
        job_name=job.name,
        job_dir=job.directory,
        status="done",
        unnormalized_variables=job.unnormalized_variables,
        raw_data_paths=(raw_path,),
        metadata={
            "job_name": job.name,
            "status": "done",
            "engine": "htcondor",
            "generation_index": job.generation_index,
            "run_id": job.run_id,
        },
    )


def test_packaged_submit_file_runs_workflow_directly_with_minimal_payload(
    tmp_path,
):
    from yadof.evaluate_manager.condor_runner import write_condor_submit_file

    workspace = _workspace(tmp_path, "submit")
    (workspace / "job_template" / "model with spaces.aedt").write_bytes(b"model")
    config = load_config(workspace)
    job = prepare_job(
        workspace,
        (0.5,),
        config=config,
        mode="distributed",
        timeout_sec=None,
        generation_index=None,
    )

    submit_path = write_condor_submit_file(
        workspace, job, config=config
    )
    text = submit_path.read_text(encoding="utf-8")

    assert "Auto-generated by yadof.evaluate_manager" in text
    assert "executable = workflow.py" in text
    assert "transfer_executable = True" in text
    assert "transfer_output_files = rawData.zip,individual_metadata.json" in text
    assert "allowed_execute_duration" not in text
    assert "request_cpus = 3" in text
    assert "request_memory = 10MB" in text
    assert "request_disk = 100KB" in text
    transfer = next(
        line for line in text.splitlines() if line.startswith("transfer_input_files")
    )
    assert "worker_misc.py" in transfer
    assert "workflow.py" not in transfer
    assert "sitecustomize.py" not in transfer
    assert "yadof_worker_package.zip" not in transfer
    assert "yadof_worker_config.json" not in transfer
    assert "model with spaces.aedt" in transfer
    assert '"model with spaces.aedt"' not in transfer
    assigned = (job.directory / "parameters_constraints.py").read_text(
        encoding="utf-8"
    )
    assert "class Parameter:" in assigned
    assert "import yadof" not in assigned
    assert not any(path.name.startswith("yadof_worker") for path in job.directory.iterdir())


def test_distributed_population_and_smoke_keep_shape_and_callback(
    tmp_path, monkeypatch
):
    from yadof.evaluate_manager import condor_runner

    workspace = _workspace(tmp_path, "dispatch")
    callbacks: list[str] = []

    def fake_run(workspace_arg, jobs, **kwargs):
        assert workspace_arg.root == workspace.resolve()
        assert kwargs["timeout_sec"] is not None
        kwargs["after_jobs_submitted"]()
        return tuple(_completed_result(job) for job in jobs)

    monkeypatch.setattr(condor_runner, "run_condor_jobs", fake_run)
    costs = evaluate_population(
        workspace,
        ((0.25,), (0.75,)),
        mode="distributed",
        after_jobs_submitted=lambda: callbacks.append("submitted"),
    )
    assert costs == ((0.25,), (0.25,))
    assert callbacks == ["submitted"]
    assert len(list_records(workspace)) == 2

    def fake_smoke(workspace_arg, jobs, **kwargs):
        assert kwargs["timeout_sec"] is None
        assert len(jobs) == 1
        return (_completed_result(jobs[0]),)

    monkeypatch.setattr(condor_runner, "run_condor_jobs", fake_smoke)
    assert run_smoke_test(workspace, mode="distributed") == ((0.25,),)


def test_distributed_submit_failure_is_per_individual_and_diagnosable(
    tmp_path, monkeypatch
):
    from yadof.evaluate_manager import condor_runner

    workspace = _workspace(tmp_path, "failure")

    def missing_condor(*_args, **_kwargs):
        raise OSError("condor_submit is unavailable")

    monkeypatch.setattr(condor_runner.subprocess, "run", missing_condor)
    costs = evaluate_population(
        workspace, ((0.25,), (0.75,)), mode="distributed", timeout_sec=0.1
    )
    assert all(math.isinf(row[0]) for row in costs)
    records = list_records(workspace)
    assert len(records) == 2
    assert all(row["status"] == "error" for row in records)
    assert all(
        row["job_metadata"]["failure_stage"] == "submit" for row in records
    )


def test_matchmaking_diagnostic_reports_failed_requirement(tmp_path, monkeypatch):
    from yadof.evaluate_manager import condor_runner

    workspace = _workspace(tmp_path, "matchmaking")
    job = prepare_job(workspace, (0.5,), mode="distributed", timeout_sec=None)
    submission = condor_runner.CondorSubmission(
        job=job,
        submit_file=job.directory / "job.sub",
        cluster_id=4249,
        submitted_at="2026-07-22T19:20:00+08:00",
        stdout="",
        stderr="",
    )
    analysis = """
The Requirements expression for job 4249.000 reduces to these conditions:

        Slots
Step   Matched  Condition
----- --------- ---------
[1]           0  TARGET.YADOF_RAMDISK is true

WARNING:  Be advised:
   No machines matched the job's constraints

Reason for last match failure: no match found
"""

    def fake_run(*_args, **_kwargs):
        return subprocess.CompletedProcess(
            args=["condor_q"], returncode=0, stdout=analysis, stderr=""
        )

    monkeypatch.setattr(condor_runner.subprocess, "run", fake_run)

    diagnostic = condor_runner.condor_matchmaking_diagnostic(submission)

    assert "failed requirement: TARGET.YADOF_RAMDISK is true" in diagnostic
    assert "no machines matched the job's constraints" in diagnostic
    assert "last match failure: no match found" in diagnostic


def test_direct_workflow_creates_flat_rawdata_zip(tmp_path):
    workspace = _workspace(tmp_path, "direct_workflow")
    job = prepare_job(workspace, (0.5,), mode="distributed", timeout_sec=None)

    result = subprocess.run(
        [sys.executable, str(job.directory / "workflow.py")],
        cwd=job.directory,
        capture_output=True,
        text=True,
        timeout=20,
        check=False,
    )

    assert result.returncode == 0, result.stdout + result.stderr
    archive_path = job.directory / "rawData.zip"
    with zipfile.ZipFile(archive_path) as archive:
        assert archive.namelist() == ["response.npz"]


def test_condor_restore_rejects_nested_rawdata_zip(tmp_path):
    from yadof.evaluate_manager.condor_runner import restore_rawdata_transfer_zip

    job_dir = tmp_path / "job"
    job_dir.mkdir()
    with zipfile.ZipFile(job_dir / "rawData.zip", "w") as archive:
        archive.writestr("rawData/response.npz", b"invalid nesting")

    error = restore_rawdata_transfer_zip(job_dir)

    assert error is not None
    assert "direct .npz file" in error
    assert not tuple((job_dir / "rawData").glob("*.npz"))


def test_resource_calibration_reads_only_the_selected_workspace(
    tmp_path, monkeypatch
):
    from yadof.evaluate_manager import resource_requests

    workspace_a = _workspace(tmp_path, "calibration_a")
    workspace_b = _workspace(tmp_path, "calibration_b")
    config_a = load_config(workspace_a)
    config_b = load_config(workspace_b)
    job_a = SimpleNamespace(generation_index=0, run_id="run-a")
    job_b = SimpleNamespace(generation_index=0, run_id="run-b")
    records_by_root = {
        workspace_a.resolve(): (
            {
                "status": "completed",
                "generation_index": None,
                "job_metadata": {
                    "engine": "htcondor",
                    "condor_memory_usage_mib": 512,
                    "condor_disk_usage_kib": 2048,
                },
            },
        ),
        workspace_b.resolve(): (),
    }

    monkeypatch.setattr(
        resource_requests.recorded_data_api,
        "list_records",
        lambda workspace: records_by_root[Path(workspace.root).resolve()],
    )
    request_a = resource_requests.request_for_job(
        workspace_a, job_a, config=config_a
    )
    request_b = resource_requests.request_for_job(
        workspace_b, job_b, config=config_b
    )
    assert request_a.source == "smoke_calibration"
    assert request_a.memory_mib == 1024
    assert request_b.source == "configured_default"
    assert request_b.memory_mib == 10


def test_time_limit_calibration_is_workspace_local(tmp_path, monkeypatch):
    from yadof.evaluate_manager import time_limits
    from yadof.evaluate_manager.types import JobSpec

    workspace_a = _workspace(tmp_path, "time_a")
    workspace_b = _workspace(tmp_path, "time_b")
    config_a = load_config(workspace_a)
    config_b = load_config(workspace_b)
    job = JobSpec(
        name="generation-zero",
        directory=workspace_a / "jobs/generation-zero",
        unnormalized_variables=(0.5,),
        generation_index=0,
        run_id="run-a",
    )
    records = {
        workspace_a.resolve(): (
            {
                "status": "completed",
                "generation_index": None,
                "recorded_at": "2026-07-18T10:00:00+00:00",
                "job_metadata": {
                    "engine": "htcondor",
                    "condor_remote_wall_clock_sec": 12.0,
                    "condor_cumulative_suspension_sec": 2.0,
                },
            },
        ),
        workspace_b.resolve(): (),
    }
    monkeypatch.setattr(
        time_limits.recorded_data_api,
        "list_records",
        lambda selected: records[Path(selected.root).resolve()],
    )

    limit_a = time_limits.time_limit_for_job(workspace_a, job, config=config_a)
    limit_b = time_limits.time_limit_for_job(workspace_b, job, config=config_b)

    assert limit_a.source == "smoke_calibration"
    assert limit_a.seconds == 20
    assert limit_b.source == "configured_fallback"
