from __future__ import annotations

from pathlib import Path

PROJECT_ROOT = Path(__file__).resolve().parent
JOBS_DIR = PROJECT_ROOT / "jobs"
SURROGATE_CHECKPOINT_DIR = PROJECT_ROOT / "surrogate" / "checkpoints"

EVALUATION_MODE = "local"

OPTIMIZE_POPULATION_SIZE = 4
OPTIMIZE_VARIABLE_COUNT = 3
OPTIMIZE_RANDOM_SEED = 20260510

SURROGATE_ALPHA = 0.10
SURROGATE_RELATIVE_ERROR_EPS = 1e-8
SURROGATE_RBF_RIDGE = 1e-8
SURROGATE_IDW_POWER = 2.0
SURROGATE_CONSTANT_ATOL = 1e-12
SURROGATE_EXACT_NEIGHBOR_RADIUS = 0.08

OPTIMIZE_SURROGATE_ENABLED = True
OPTIMIZE_SURROGATE_ALPHA = 4
OPTIMIZE_SURROGATE_BETA = 2
OPTIMIZE_SURROGATE_GAMMA = 0.5
OPTIMIZE_REFILL_ATTEMPTS = 8
OPTIMIZE_ARCHIVE_KEY_DECIMALS = 10
OPTIMIZE_CROSSOVER_PROBABILITY = 0.80
OPTIMIZE_MUTATION_PROBABILITY = 0.35
OPTIMIZE_MUTATION_SIGMA = 0.12
