from __future__ import annotations

from pathlib import Path

PROJECT_ROOT = Path(__file__).resolve().parent
JOBS_DIR = Path("R:/")
SURROGATE_CHECKPOINT_DIR = PROJECT_ROOT / "surrogate" / "checkpoints"

EVALUATION_MODE = "local"
# Number of local workflow subprocesses to run at once. Keep this at 1 for
# simulator adapters that cannot safely run concurrently; raise it for pure
# Python or otherwise parallel-safe workflows.
LOCAL_EVALUATION_MAX_WORKERS = 1
HTCONDOR_SUBMIT_EXE = "condor_submit"
HTCONDOR_REMOVE_EXE = "condor_rm"
HTCONDOR_POLL_SEC = 30.0
HTCONDOR_REQUEST_CPUS = 4
HTCONDOR_REQUEST_MEMORY = "8GB"
HTCONDOR_REQUEST_DISK = "2GB"
HTCONDOR_ENVIRONMENT = "USERPROFILE=._home;HOME=._home;APPDATA=._appdata;LOCALAPPDATA=._localappdata;TEMP=._tmp;TMP=._tmp"
HTCONDOR_LOAD_PROFILE = True
HTCONDOR_RUN_AS_OWNER = False
HTCONDOR_REQUIREMENTS = '(OpSys == "WINDOWS")'

OPTIMIZE_POPULATION_SIZE = 100
OPTIMIZE_RANDOM_SEED = 20260510

# Conditional INR deep-ensemble surrogate settings.
SURROGATE_RELATIVE_ERROR_EPS = 1e-8
SURROGATE_CONSTANT_ATOL = 1e-12
SURROGATE_TARGET_SCALE_FLOOR = 1e-6
SURROGATE_TORCH_DEVICE = "auto"
SURROGATE_INR_EPOCHS = 32
SURROGATE_INR_ENSEMBLE_SIZE = 3
SURROGATE_INR_BATCH_SIZE = 16
SURROGATE_INR_LR = 1e-3
SURROGATE_INR_WEIGHT_DECAY = 1e-5
SURROGATE_INR_LOSS_BETA = 0.05
SURROGATE_INR_RELATIVE_LOSS_WEIGHT = 0.15
SURROGATE_INR_RELATIVE_LOSS_EPS = 0.05
SURROGATE_RAWDATA_IMPORTANCE_FLOOR = 0.25
SURROGATE_RAWDATA_IMPORTANCE_BOOST = 2.0
SURROGATE_INR_X_LATENT_DIM = 96
SURROGATE_INR_FIELD_EMB_DIM = 12
SURROGATE_INR_COORD_FOURIER_FEATURES = 24
SURROGATE_INR_HIDDEN_DIM = 192
SURROGATE_INR_HIDDEN_LAYERS = 3
SURROGATE_INR_TRAIN_QUERY_CHUNK = 4096
SURROGATE_INR_SAMPLE_BATCH_EVAL = 64
SURROGATE_INR_QUERY_BATCH_EVAL = 8192
SURROGATE_INR_BOOTSTRAP_MEMBERS = True
SURROGATE_INR_BOOTSTRAP_FRACTION = 1.0

# GPSAF surrogate-assistance controls.
# Set OPTIMIZE_SURROGATE_ALPHA = 1 and OPTIMIZE_SURROGATE_BETA = 0 to run the
# same GPSAF entrypoint without importing or calling project.surrogate.
# Increase alpha above 1 to add surrogate tournament pressure; increase beta
# above 0 to run simulated baseline-optimizer iterations on surrogate costs.
OPTIMIZE_SURROGATE_ALPHA = 3
OPTIMIZE_SURROGATE_BETA = 3
OPTIMIZE_SURROGATE_GAMMA = 0.5
OPTIMIZE_SURROGATE_EXPLORATION_FRACTION = 0.10

OPTIMIZE_NSGA3_REF_DIR_METHOD = "das-dennis"
OPTIMIZE_NSGA3_PARTITIONS = None
OPTIMIZE_REFILL_ATTEMPTS = 8
OPTIMIZE_ARCHIVE_KEY_DECIMALS = 10
OPTIMIZE_CROSSOVER_PROBABILITY = 0.80
OPTIMIZE_MUTATION_PROBABILITY = 0.35
OPTIMIZE_CROSSOVER_ETA = 20.0
OPTIMIZE_MUTATION_ETA = 20.0
OPTIMIZE_DIM_MUT_PER_INDIVIDUAL = 1.0
