from __future__ import annotations

from pathlib import Path

PROJECT_ROOT = Path(__file__).resolve().parent
JOBS_DIR = PROJECT_ROOT / "jobs"
SURROGATE_CHECKPOINT_DIR = PROJECT_ROOT / "surrogate" / "checkpoints"

EVALUATION_MODE = "local"

OPTIMIZE_POPULATION_SIZE = 100
OPTIMIZE_RANDOM_SEED = 20260510

# Conditional INR deep-ensemble surrogate settings.
# SURROGATE_ALPHA is the minimum relative interval width around predicted costs;
# it is separate from OPTIMIZE_SURROGATE_ALPHA below.
SURROGATE_ALPHA = 0.10
SURROGATE_RELATIVE_ERROR_EPS = 1e-8
SURROGATE_CONSTANT_ATOL = 1e-12
SURROGATE_TARGET_SCALE_FLOOR = 1e-6
SURROGATE_EXACT_NEIGHBOR_RADIUS = 0.08
SURROGATE_TORCH_DEVICE = "auto"
SURROGATE_INR_EPOCHS = 32
SURROGATE_INR_ENSEMBLE_SIZE = 3
SURROGATE_INR_BATCH_SIZE = 16
SURROGATE_INR_LR = 1e-3
SURROGATE_INR_WEIGHT_DECAY = 1e-5
SURROGATE_INR_LOSS_BETA = 0.05
SURROGATE_INR_RELATIVE_LOSS_WEIGHT = 0.15
SURROGATE_INR_X_LATENT_DIM = 96
SURROGATE_INR_FIELD_EMB_DIM = 12
SURROGATE_INR_COORD_FOURIER_FEATURES = 24
SURROGATE_INR_HIDDEN_DIM = 192
SURROGATE_INR_HIDDEN_LAYERS = 3
SURROGATE_INR_TRAIN_QUERY_CHUNK = 4096
SURROGATE_INR_SAMPLE_BATCH_EVAL = 64
SURROGATE_INR_QUERY_BATCH_EVAL = 8192
SURROGATE_INR_BOOTSTRAP_MEMBERS = True
SURROGATE_INR_BOOTSTRAP_FRACTION = 1.0

OPTIMIZE_CHECKPOINT_DIR = PROJECT_ROOT / "optimize" / "checkpoints"

# GPSAF surrogate-assistance controls.
# Set OPTIMIZE_SURROGATE_ALPHA = 1 and OPTIMIZE_SURROGATE_BETA = 0 to run the
# same GPSAF entrypoint without importing or calling project.surrogate.
# Increase alpha above 1 to add surrogate tournament pressure; increase beta
# above 0 to run simulated baseline-optimizer iterations on surrogate costs.
OPTIMIZE_SURROGATE_ALPHA = 1
OPTIMIZE_SURROGATE_BETA = 0
OPTIMIZE_SURROGATE_GAMMA = 0.5

OPTIMIZE_REFILL_ATTEMPTS = 8
OPTIMIZE_ARCHIVE_KEY_DECIMALS = 10
OPTIMIZE_CROSSOVER_PROBABILITY = 0.80
OPTIMIZE_MUTATION_PROBABILITY = 0.35
OPTIMIZE_CROSSOVER_ETA = 20.0
OPTIMIZE_MUTATION_ETA = 20.0
OPTIMIZE_DIM_MUT_PER_INDIVIDUAL = 1.0
