"""Plot styling constants for the cost viewer."""

MAX_VISIBLE_PARETO = 10
TREND_LINE_ALPHA = 0.25
TREND_LINE_WIDTH = 2.0
AVG_TREND_LINE_WIDTH = 4.0
HV_LINE_COLOR = "#0066CC"
HV_SHADE_ALPHA = 0.2
EVENT_LINE_ALPHA = TREND_LINE_ALPHA
EVENT_LINE_WIDTH = 1.2
EVENT_DASH_LENGTH = 4.0
OPT_LINE_STYLE = (0.0, (EVENT_DASH_LENGTH, EVENT_DASH_LENGTH))
HASH_LINE_STYLE = (
    EVENT_DASH_LENGTH,
    (EVENT_DASH_LENGTH, EVENT_DASH_LENGTH),
)
SCATTER_ALPHA = 0.6
MIN_SCATTER_ALPHA = 0.15
OPT_LINE_COLOR = "black"
HASH_LINE_COLOR = "#FFAA00"
OPT_LINE_LABEL = "Opt. start"
HASH_LINE_LABEL = "Hash change"
EVENT_LINE_LABELS = (OPT_LINE_LABEL, HASH_LINE_LABEL)
PLOT_COLORS = [
    "#FF0000",
    "#FFAA00",
    "#58A500",
    "#00BFE9",
    "#2000AA",
    "#960096",
    "#808080",
]
PLOT_MARKERS = ["o", "s", "D", "^", "v", "<", ">"]
PLOT_FIGSIZE = (5.5, 3.5)
PLOT_DPI = 600
PLOT_FONT_SIZE = 10
PLOT_TITLE_FONT_SIZE = 11
PLOT_TICK_FONT_SIZE = 8
PLOT_LEGEND_FONT_SIZE = 7
PLOT_LEGEND_FRAME_ALPHA = 0.6
PLOT_LEGEND_EDGE_PAD = 0.015
PLOT_LEGEND_GAP = 0.01
PLOT_GENERATION_FONT_SIZE = 8
PLOT_TIGHT_LAYOUT_PAD = 0.6
AXIS_LINE_WIDTH = 0.8
GRID_LINE_WIDTH = 0.4
SCATTER_MARKER_SIZE = 3.0
SCATTER_EDGE_LINE_WIDTH = 0.4
PARETO_MARKER_AREA = 60.0
PARETO_EDGE_LINE_WIDTH = 0.75
GENERATION_SHADE_COLOR = "black"
GENERATION_SHADE_ALPHA = 0.1
GENERATION_LABEL_Y = 0.98
MAX_REPORTED_ISSUES = 10
