from . import conditional_inr as _conditional_inr_package
from .api import (
    ConditionalINRComponent,
    MaterializedRawDataPosterior,
    RAWDATA_POSTERIOR_PROTOCOL,
    RAWDATA_POSTERIOR_PROTOCOL_VERSION,
    RawDataFunctionDraw,
    RawDataPosterior,
    RawDataPosteriorDiagnostics,
    RawDataPosteriorSampler,
    RawDataPosteriorSurrogate,
    SUPPORT_CONTINUOUS_OR_UNKNOWN,
    SUPPORT_FINITE,
    conditional_inr,
    deactivate_workspace,
    ensure_fresh_enough,
    has_trained_state,
    latest_state_generation,
    predict_population,
    posterior_capability_identity,
    project_rawdata_sampler,
    require_rawdata_posterior_surrogate,
    start_training,
    train,
    wait_for_pending_training,
)

# Load the private package before rebinding the same public factory name. This keeps
# ``yadof.surrogate.conditional_inr`` callable after private implementation imports.

__all__ = [
    "ConditionalINRComponent",
    "MaterializedRawDataPosterior",
    "RAWDATA_POSTERIOR_PROTOCOL",
    "RAWDATA_POSTERIOR_PROTOCOL_VERSION",
    "RawDataFunctionDraw",
    "RawDataPosterior",
    "RawDataPosteriorDiagnostics",
    "RawDataPosteriorSampler",
    "RawDataPosteriorSurrogate",
    "SUPPORT_CONTINUOUS_OR_UNKNOWN",
    "SUPPORT_FINITE",
    "conditional_inr",
    "deactivate_workspace",
    "ensure_fresh_enough",
    "has_trained_state",
    "latest_state_generation",
    "predict_population",
    "posterior_capability_identity",
    "project_rawdata_sampler",
    "require_rawdata_posterior_surrogate",
    "start_training",
    "train",
    "wait_for_pending_training",
]
