[CmdletBinding()]
param()

$ErrorActionPreference = "Stop"

$scriptDir = Split-Path -Parent $PSCommandPath
$managerIpFile = Join-Path $scriptDir "manager_ip.txt"
$queryConfig = Join-Path $scriptDir "show_slots.condor_config"

$condorRoot = if (Test-Path -LiteralPath "D:\condor" -PathType Container) {
    "D:\condor"
}
elseif ($env:CONDOR_LOCATION) {
    $env:CONDOR_LOCATION
}
else {
    "D:\condor"
}

$condorBin = Join-Path $condorRoot "bin"
$condorStatus = Join-Path $condorBin "condor_status.exe"

if (-not (Test-Path -LiteralPath $condorStatus)) {
    $cmd = Get-Command condor_status -ErrorAction SilentlyContinue
    if ($cmd) {
        $condorStatus = $cmd.Source
    }
    else {
        throw "Could not find condor_status.exe. Expected $condorStatus"
    }
}

$managerIp = $null
if (Test-Path -LiteralPath $managerIpFile -PathType Leaf) {
    $managerIp = @(Get-Content -LiteralPath $managerIpFile |
        ForEach-Object { $_.Trim() } |
        Where-Object { $_ -and -not $_.StartsWith("#") } |
        Select-Object -First 1)[0]
}

$configCandidates = @(
    [Environment]::GetEnvironmentVariable("CONDOR_CONFIG", "Machine"),
    $env:CONDOR_CONFIG,
    (Join-Path $condorRoot "condor_config"),
    (Join-Path $condorRoot "etc\condor_config"),
    "D:\condor\condor_config",
    "D:\condor\etc\condor_config"
) | Where-Object { $_ } | Select-Object -Unique

$condorConfig = $null
foreach ($candidate in $configCandidates) {
    if (Test-Path -LiteralPath $candidate -PathType Leaf) {
        $condorConfig = $candidate
        break
    }
}

if (-not $condorConfig) {
    if (-not $managerIp) {
        throw "No HTCondor config file was found and manager_ip.txt is missing. Re-run setup_machine_1_manager.cmd, then copy manager_ip.txt here."
    }

    $content = @(
        "# Generated by show_slots.ps1 for querying the pool only.",
        "CONDOR_HOST = $managerIp",
        "COLLECTOR_HOST = `$`(CONDOR_HOST`):9618",
        "SEC_DEFAULT_AUTHENTICATION = OPTIONAL",
        "SEC_DEFAULT_ENCRYPTION = OPTIONAL",
        "SEC_DEFAULT_INTEGRITY = OPTIONAL"
    ) -join [Environment]::NewLine
    [IO.File]::WriteAllText($queryConfig, $content + [Environment]::NewLine, [Text.Encoding]::ASCII)
    $condorConfig = $queryConfig
    Write-Warning "No installed HTCondor config was found. Generated query-only config: $queryConfig"
}

$env:CONDOR_CONFIG = $condorConfig
Write-Host "Using CONDOR_CONFIG=$condorConfig"

Write-Host ""
if ($managerIp) {
    Write-Host "Slots from pool ${managerIp}:9618"
    & $condorStatus -pool "${managerIp}:9618" -af Name Machine Cpus Memory OpSys
}
else {
    Write-Host "Slots from configured default pool"
    & $condorStatus -af Name Machine Cpus Memory OpSys
}

Write-Host ""
Write-Host "Totals:"
if ($managerIp) {
    & $condorStatus -pool "${managerIp}:9618" -total
}
else {
    & $condorStatus -total
}
