[CmdletBinding()]
param()

$ErrorActionPreference = "Stop"

$scriptDir = Split-Path -Parent $PSCommandPath
$managerIpFile = Join-Path $scriptDir "manager_ip.txt"
$queryConfig = Join-Path $scriptDir "show_slots.condor_config"

function Get-CondorBinCandidates {
    $dirs = New-Object System.Collections.Generic.List[string]
    if ($env:CONDOR_LOCATION) {
        $dirs.Add((Join-Path $env:CONDOR_LOCATION "bin"))
    }
    foreach ($dir in @(
        "$env:ProgramFiles\HTCondor\bin",
        "$env:ProgramFiles\Condor\bin"
    )) {
        if ($dir) {
            $dirs.Add($dir)
        }
    }
    $programFilesX86 = [Environment]::GetEnvironmentVariable("ProgramFiles(x86)")
    if ($programFilesX86) {
        $dirs.Add((Join-Path $programFilesX86 "HTCondor\bin"))
        $dirs.Add((Join-Path $programFilesX86 "Condor\bin"))
    }
    return @($dirs | Where-Object { $_ } | Select-Object -Unique)
}

function Find-CondorStatus {
    $cmd = Get-Command condor_status -ErrorAction SilentlyContinue
    if ($cmd) {
        return $cmd.Source
    }
    foreach ($dir in Get-CondorBinCandidates) {
        $candidate = Join-Path $dir "condor_status.exe"
        if (Test-Path -LiteralPath $candidate -PathType Leaf) {
            return $candidate
        }
    }
    throw "Could not find condor_status.exe. Put HTCondor on PATH, set CONDOR_LOCATION, or install it under Program Files."
}

function Read-ManagerIp {
    if (-not (Test-Path -LiteralPath $managerIpFile -PathType Leaf)) {
        return $null
    }
    return @(Get-Content -LiteralPath $managerIpFile |
        ForEach-Object { $_.Trim() } |
        Where-Object { $_ -and -not $_.StartsWith("#") } |
        Select-Object -First 1)[0]
}

$condorStatus = Find-CondorStatus
$condorBin = Split-Path -Parent $condorStatus
$condorRoot = Split-Path -Parent $condorBin
$managerIp = Read-ManagerIp

$configCandidates = @(
    [Environment]::GetEnvironmentVariable("CONDOR_CONFIG", "Machine"),
    $env:CONDOR_CONFIG,
    (Join-Path $condorRoot "condor_config"),
    (Join-Path $condorRoot "etc\condor_config")
) | Where-Object { $_ } | Select-Object -Unique

$condorConfig = $null
foreach ($candidate in $configCandidates) {
    if (Test-Path -LiteralPath $candidate -PathType Leaf) {
        $condorConfig = $candidate
        break
    }
}

if (-not $condorConfig) {
    if (-not $managerIp) {
        throw "No HTCondor config file was found and manager_ip.txt is missing. Re-run setup_machine_1_manager.cmd, then copy manager_ip.txt here."
    }

    $content = @(
        "# Generated by show_slots.ps1 for querying the pool only.",
        "CONDOR_HOST = $managerIp",
        "COLLECTOR_HOST = `$`(CONDOR_HOST`):9618",
        "SEC_DEFAULT_AUTHENTICATION = OPTIONAL",
        "SEC_DEFAULT_ENCRYPTION = OPTIONAL",
        "SEC_DEFAULT_INTEGRITY = OPTIONAL"
    ) -join [Environment]::NewLine
    [IO.File]::WriteAllText($queryConfig, $content + [Environment]::NewLine, [Text.Encoding]::ASCII)
    $condorConfig = $queryConfig
    Write-Warning "No installed HTCondor config was found. Generated query-only config: $queryConfig"
}

$env:CONDOR_CONFIG = $condorConfig
Write-Host "Using condor_status=$condorStatus"
Write-Host "Using CONDOR_CONFIG=$condorConfig"

Write-Host ""
if ($managerIp) {
    Write-Host "Slots from pool ${managerIp}:9618"
    & $condorStatus -pool "${managerIp}:9618" -af Name Machine Cpus Memory OpSys
}
else {
    Write-Host "Slots from configured default pool"
    & $condorStatus -af Name Machine Cpus Memory OpSys
}

Write-Host ""
Write-Host "Totals:"
if ($managerIp) {
    & $condorStatus -pool "${managerIp}:9618" -total
}
else {
    & $condorStatus -total
}
